# Generated by Django 6.0.7 on 2026-08-05 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password reset')], max_length=32)),
                ('expiration_date', models.DateTimeField()),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_auth_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expiration_date'],
                'indexes': [models.Index(fields=['user', 'purpose', 'validated_at'], name='users_email_user_id_895790_idx')],
            },
        ),
    ]
