# Generated by Django 6.0.7 on 2026-08-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='Default', help_text='Short label for this SMTP configuration.', max_length=255, verbose_name='Alias')),
                ('host', models.CharField(default='smtp.gmail.com', help_text='Example: smtp.gmail.com', max_length=255, verbose_name='SMTP host')),
                ('port', models.PositiveIntegerField(default=587, help_text='SMTP port (typically 587 for TLS or 465 for SSL).', verbose_name='Port')),
                ('username', models.CharField(blank=True, default='', help_text='Leave blank for an open relay.', max_length=255, verbose_name='Username')),
                ('password', models.CharField(blank=True, default='', help_text='App password or SMTP password.', max_length=255, verbose_name='Password')),
                ('from_email', models.CharField(default='App <noreply@example.com>', help_text='From header, e.g. App <noreply@example.com>.', max_length=255, verbose_name='From email')),
                ('reply_to', models.CharField(blank=True, default='', help_text='Optional Reply-To address. Defaults to From email.', max_length=255, verbose_name='Reply-To')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('timeout', models.PositiveIntegerField(blank=True, null=True, verbose_name='Timeout (seconds)')),
            ],
            options={
                'verbose_name': 'SMTP server',
                'verbose_name_plural': 'SMTP servers',
            },
        ),
    ]
